site_title = "Josh's Blog"
base_url = "http://localhost"
theme = "dracula"
posts_per_page = 5
content_dir = "/content"

[author]
name = "Josh Hartwig"
bio = "Just another developer"
email = "randomguy@aol.com"