services:
  blogo:
    image: ghcr.io/joshhartwig/blogo:latest
    container_name: blogo
    restart: unless-stopped
    ports:
      - "3999:3999"
    volumes:
      - ./content:/app/content:ro
    command:
